<a href="https://colab.research.google.com/github/Vaishak1044/Fundamentals_ML_Internship_2023/blob/main/2_NumPy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# NumPy

Numpy is a Python library for creating and manipulating matrices, the main data structure used by ML algorithms. Matrices are mathematical objects used to store values in rows and columns.

NumPy is a powerful library in Python that provides support for arrays and matrices. An array in NumPy is a multi-dimensional, homogeneous data structure that can store elements of the same data type.


# Import NumPy module

In [ ]:
import numpy as np 

# Creating nd Arrays

Create an n-dimensional array: To create an ndarray, we can pass a list, tuple or any array-like object into the array() method, and it will be converted into an ndarray

In [ ]:
arr = np.array([1, 2, 3, 4, 5])

print(arr)

print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [ ]:
#find mean, median for numpy array containing 10 elements
arr = np.array([1,2,3,4,5,6,7,8,9,10])
mean=0

for i in arr:
  mean+=i

print(mean/len(arr))

5.5


Create a 0-D array

NumPy arrays have an attribute called **shape** that returns a tuple with each index having the number of corresponding elements.

NumPy Arrays provides the **ndim** attribute that returns an integer that tells us how many dimensions the array have.

In [ ]:
arr = np.array(42)
print(arr)
print(arr.ndim)
print(arr.shape)

0
()


Create 1-D array: To create a one-dimensional array specify a layer of square brackets
An array that has 0-D arrays as its elements is called uni-dimensional or 1-D array

In [ ]:
arr = np.array([1, 2, 3, 4, 5])
print(arr)
print(arr.ndim)
print(arr.shape)

[1 2 3 4 5]
1
(5,)


Create 2-D array: To create a two-dimensional array specify an extra layer of square brackets
An array that has 1-D arrays as its elements is called a 2-D array. These are often used to represent matrix or 2nd order tensors.

In [ ]:
arr = np.array([[1, 2, 3], [4, 5, 6],[6,7,8]])
print(arr)
print(arr.ndim)
print(arr.shape)

[[1 2 3]
 [4 5 6]
 [6 7 8]]
2
(3, 3)


Create 3-D array: An array that has 2-D arrays (matrices) as its elements is called 3-D array.
These are often used to represent a 3rd order tensor.

In [ ]:
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
print(arr)
print(arr.ndim)
print(arr.shape)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
3
(2, 2, 3)


# NOTE: 
        A 0-D array has 0 square brackets
        1-D array has 1 square brackets at the start and end
        2-D array has 2 square brackets at the start and end
        3-D array has 3 square brakets at the start and end

Higher Dimensional Arrays: An array can have any number of dimensions.
When the array is created, you can define the number of dimensions by using the ndmin argument.

In [ ]:
arr = np.array([[1, 2, 3, 4],[3,4,5,6]], ndmin=5)
print(arr)
print(arr.shape)


[[[[[1 2 3 4]
    [3 4 5 6]]]]]
(1, 1, 1, 2, 4)


In [ ]:
a = np.array([1, 2, 3, 4])
b = np.array([5, 6, 7, 8])

# Add the arrays
c = a + b
print("Addition of arrays a and b:", c)

# Multiply the arrays
d = a * b
print("Multiplication of arrays a and b:", d)

In [ ]:
f = np.dot(a, b)
print("Dot product of arrays a and b:", f)

In [ ]:
Z = np.random.randint((16,4))
print(Z)

# NumPy Array Indexing

Array indexing is the same as accessing an array element.

You can access an array element by referring to its index number.

The indexes in NumPy arrays start with 0, meaning that the first element has index 0, and the second has index 1 etc.

In [ ]:
arr = np.array([1, 2, 3, 4])

print(arr[0])

1


Get third and fourth elements from the following array and add them.

In [ ]:
#@title Get third and fourth elements from the following array and add them.
import numpy as np
arr = np.array([1, 2, 3, 4])

print(arr[2] + arr[3])

7


In [ ]:
sum = 0
for i in arr:
  sum += i
print(sum)

10


Access 2-D Arrays: To access elements from 2-D arrays we can use comma separated integers representing the dimension and the index of the element.

Think of 2-D arrays like a table with **rows** and **columns**, where the **dimension** represents the **row** and the **index** represents the **column**.

In [ ]:
arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])

print('2nd element on 1st row: ', arr[1, 1:5])

2nd element on 1st row:  [ 7  8  9 10]


In [ ]:
#@title Access the element on the 2nd row, 5th column
arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])

print('5th element on 2nd row: ', arr[1, 4])

5th element on 2nd row:  10


Access 3-D Arrays: To access elements from 3-D arrays we can use comma separated integers representing the dimensions and the index of the element.

In [ ]:
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

print('3rd element of the 2nd array of the 1st array: ',arr[0, 1, 2])

3rd element of the 2nd array of the 1st array:  6


Negative Indexing

In [ ]:
arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])

print('Last element from 2nd dim: ', arr[1, -1])

#print('Last element from 2nd dim: ', arr[-1, -1])

Last element from 2nd dim:  10


# NumPy Array Slicing

  Slicing in python means taking elements from one given index to another given index.

We pass slice instead of index like this: [start:end].

We can also define the step, like this: [start:end:step].

If we don't pass start its considered 0

If we don't pass end its considered length of array in that dimension

If we don't pass step its considered 1

Slice elements from index 1 to index 5 from the following array:

In [ ]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[1:5])

[2 3 4 5]


Slice elements from index 4 to the end of the array

In [ ]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[4:])

[5 6 7]


Negative Slicing

In [ ]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[-3:-1])

[5 6]


Slicing with Step

In [ ]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[1:5:2])

[2 4]


Slicing **2-D Arrays**

From the second element, slice elements from index 1 to index 4 (not included):

In [ ]:
arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

print(arr[1, 1:4])

[7 8 9]


In [ ]:
#@title From both elements, return index 2:
arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

print(arr[0:2, 2])

[3 8]


In [ ]:
#@title From both elements, slice index 1 to index 4 (not included), this will return a 2-D array:

arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

print(arr[0:2, 1:4])


[[2 3 4]
 [7 8 9]]


# NumPy Data types

**Data Types in Python**
By default Python have these data types:

*strings* - used to represent text data, the text is given under quote marks. e.g. "ABCD"

*integer* - used to represent integer numbers. e.g. -1, -2, -3

*float* - used to represent real numbers. e.g. 1.2, 42.42

*boolean* - used to represent True or False.

*complex* - used to represent complex numbers. e.g. 1.0 + 2.0j, 1.5 + 2.5j

------------------------------------------------------------------------

**Data Types in NumPy**
NumPy has some extra data types, and refer to data types with one character, like i for integers, u for unsigned integers etc.

Below is a list of all data types in NumPy and the characters used to represent them.

i - integer

b - boolean

u - unsigned integer

f - float

c - complex float

m - timedelta

M - datetime

O - object

S - string

U - unicode string

V - fixed chunk of memory for other type ( void )

Checking the Data Type of an Array

In [ ]:
arr = np.array([1, 2, 3, 4])

print(arr.dtype)

int64


Get the data type of an array containing strings:

In [ ]:
arr = np.array(['apple', 'banana', 'cherry'])

print(arr.dtype)

<U6


Creating Arrays With a Defined Data Type

In [ ]:
arr = np.array([1, 2, 3, 4], dtype='S')

print(arr)
print(arr.dtype)

[b'1' b'2' b'3' b'4']
|S1


**NOTE: above output, b --> byte, for above example it means byte String**

For i, u, f, S and U we can define size as well.

In [ ]:
arr = np.array([1, 2, 3, 4], dtype='i4')

print(arr)
print(arr.dtype)

[1 2 3 4]
int32


# NumPy Array Iterating
  Iterating means going through elements one by one.

  As we deal with multi-dimensional arrays in numpy, we can do this using basic for loop of python.

  If we iterate on a 1-D array it will go through each element one by one.

Iterate on the elements of the following 1-D array:

In [ ]:
arr = np.array([1, 2, 3])

for x in arr:
  print(x)

1
2
3


Iterate on the elements of the following 2-D array:

In [ ]:
arr = np.array([[1, 2, 3], [4, 5, 6]])

for x in arr:
  print(x)

[1 2 3]
[4 5 6]


To return the actual values, the scalars, we have to iterate the arrays in each dimension

In [ ]:
arr = np.array([[1, 2, 3], [4, 5, 6]])

for x in arr:
  for y in x:
    print(y)

1
2
3
4
5
6


Iterate on the elements of the following 3-D array:

In [ ]:
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

for x in arr:
  print(x)

[[1 2 3]
 [4 5 6]]
[[ 7  8  9]
 [10 11 12]]


Iterate down to the scalars:

In [ ]:
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

for x in arr:
  for y in x:
    for z in y:
      print(z)

1
2
3
4
5
6
7
8
9
10
11
12


# Iterating Arrays Using nditer()
  
  
  The function nditer() is a helping function that can be used from very basic to very advanced iterations. It solves some basic issues which we face in iteration, lets go through it with examples.


Iterating on Each Scalar Element
  In basic for loops, iterating through each scalar of an array we need to use n for loops which can be difficult to write for arrays with very high dimensionality.

Iterate through the following 3-D array:

In [ ]:
arr = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])

for x in np.nditer(arr):
  print(x)

1
2
3
4
5
6
7
8


# Populate arrays with sequences of numbers

In [ ]:
arr = np.arange(5, 12)
print(arr)
print(arr.shape)
print(arr.ndim)

[ 5  6  7  8  9 10 11]
(7,)
1


In [ ]:
#arrange with step size
arr = np.arange(5, 12, 3)
print(arr)
print(arr.shape)
print(arr.ndim)

[ 5  8 11]
(3,)
1


# Populate arrays with random numbers



numpy.random.randint() fills random integer values
Syntax: numpy.random.randint(low, high=None, size=None, dtype=’l’)
  
  where size = [int or tuple of ints, optional] Output shape. If the given shape is, e.g., (m, n, k), then m * n * k samples are drawn. Default is None, in which case a single value is returned.
  
  dtype : [optional] Desired output data-type.

**Note:**The numpy.random.rand() function creates an array of specified shape and fills it with random values, its syntax is different than randint

Randomly constructing 1D array 

In [ ]:
arr = np.random.randint(low=50, high=101, size=(6))
print(arr);

[100  80  70  52  95  84]


Randomly constructing 2D array

In [ ]:
arr = np.random.randint(low=50, high=101, size=(6,2))
print(arr)

[[66 91]
 [58 74]
 [58 96]
 [81 96]
 [82 93]
 [69 52]]


In [ ]:
#@title Write a program to create 16 batches with each batch having 4 elements where each value can range from 0 to 3
arr = np.random.randint(low=0, high=64, size=(16,4))
print(arr)


[[36 13 56 39]
 [56 22 46 51]
 [58 32 46 32]
 [32 39 57 31]
 [ 7 16 49 61]
 [18 43  8 54]
 [10  2 47 55]
 [36  2 44 59]
 [32 58 29 18]
 [60 54 52 51]
 [49 11 21  9]
 [17 54 61  9]
 [30 28 61 10]
 [57 27 27  0]
 [16  0 41 40]
 [23 59 50 16]]


In [ ]:
arr = np.random.randint(low=50, high=101, size=(3,3,3))
print(arr)

[[[82 51 80]
  [84 94 97]
  [98 54 84]]

 [[82 83 98]
  [87 72 65]
  [87 55 90]]

 [[86 85 71]
  [72 52 94]
  [91 60 94]]]


# Mathematical operation on NumPy operands

If you want to add or subtract two arrays, linear algebra requires that the two operands have the same dimensions. Furthermore, if you want to multiply two arrays, linear algebra imposes strict rules on the dimensional compatibility of operands. Fortunately, NumPy uses a trick called broadcasting to virtually expand the smaller operand to dimensions compatible for linear algebra. For example, the following operation uses broadcasting to add 2.0 to the value of every item in the array created in the previous code cell:

In [ ]:
arr = np.array([[2,3,4],[4,5,6]])
print(arr + 2)
print(arr*2)

[[4 5 6]
 [6 7 8]]
[[ 4  6  8]
 [ 8 10 12]]


In [ ]:
arr1=np.array([[1,2,3],[5,6,7]])
arr2=np.array([2])
arr3=arr1+arr2
print(arr3)
print(arr3.ndim)

[[3 4 5]
 [7 8 9]]
2


**Create a Linear Dataset**

Create a simple dataset consisting of a single feature and a label as follows:

1. Assign a sequence of integers from 6 to 20 (inclusive) to a NumPy array named feature.

2. Assign 15 values to a NumPy array named label such that:

    
    label = (3)(feature) + 4

For example, the first value for label should be:
    
    label = (3)(6) + 4 = 22

In [ ]:
feature = np.arange(6,21)
label = 3* feature + 4

print(feature)
print(label)

[ 6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
[22 25 28 31 34 37 40 43 46 49 52 55 58 61 64]


In [ ]:
#add noise
noise = np.random.random(15)*2 - 2
print(noise)
label=label+noise
print(label)

[-1.31684178 -0.71890651 -0.45795076 -1.84507574 -1.27826447 -1.78587304
 -1.66489536 -1.49836011 -1.69290921 -1.79713505 -1.33567005 -1.94499324
 -1.16550113 -0.78117982 -1.90553436]
[18.83162607 22.44663928 25.62302273 27.1789464  30.91735138 33.37825832
 36.52791524 39.62681505 42.4095198  45.24791457 48.68695484 51.2427384
 54.89278244 58.21959371 60.25532997]
